name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Install Rust toolchain
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Step 3: Cache Cargo dependencies
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # Step 4: Build the project
    - name: Build
      run: cargo build --verbose

    # Step 5: Run tests
    - name: Run tests
      run: cargo test --verbose
